export const environment = {
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  PORT: 'PORT',
  HOST_API: 'HOST_API',
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',

  CLOUD_NAME: 'CLOUD_NAME',
  CLOUD_API_KEY: 'CLOUD_API_KEY',
  CLOUD_API_SECRET: 'CLOUD_API_SECRET',
};
